const PROJECTS = [
  {
    id: 'gymtr',
    title: 'GYM TR',
    category: 'Fitness & Sports',
    categoryAr: 'لياقة بدنية ورياضة',
    shortDesc: 'A high-energy gym website that converts visitors into members with bold visuals and frictionless UX.',
    shortDescAr: 'موقع صالة رياضية عالي الطاقة يحوّل الزوار إلى أعضاء بتصميم جريء وتجربة مستخدم سلسة.',
    tags: ['Fitness', 'Conversion', 'Sports'],
    tagsAr: ['لياقة', 'تحويل', 'رياضة'],
    liveUrl: 'https://mohameddk123.github.io/gym/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/gym/',
    featured: true,
    problem: 'The gym needed a digital presence that matched its brand intensity and turned online visitors into paying members — fast.',
    problemAr: 'احتاجت الصالة الرياضية إلى حضور رقمي يعكس شدة علامتها التجارية ويحوّل الزوار إلى أعضاء دافعين — وبسرعة.',
    solution: 'Designed a bold, high-contrast website with dynamic hero sections, class schedules, trainer profiles, and a WhatsApp-first booking flow that removes all friction.',
    solutionAr: 'صممنا موقعاً جريئاً عالي التباين مع أقسام بطولية ديناميكية، وجداول الدروس، وملفات المدربين، ونظام حجز عبر واتساب يزيل كل عوائق التسجيل.',
    result: '3× increase in online inquiries within the first month. Members reported the website alone convinced them to choose this gym before even visiting.',
    resultAr: 'زيادة ثلاثية في الاستفسارات الإلكترونية خلال الشهر الأول. أفاد الأعضاء بأن الموقع وحده أقنعهم باختيار هذه الصالة قبل زيارتها.',
    year: '2024',
    color: '#FF7A00'
  },
  {
    id: 'carturkey',
    title: 'Car Turkey',
    category: 'Automotive',
    categoryAr: 'سيارات',
    shortDesc: 'A premium digital showroom for a Turkish car dealership with sophisticated design and seamless inquiry system.',
    shortDescAr: 'صالة عرض رقمية فاخرة لوكالة سيارات تركية بتصميم راقٍ ونظام استفسار سلس.',
    tags: ['Automotive', 'Luxury', 'Leads'],
    tagsAr: ['سيارات', 'فاخر', 'عملاء محتملون'],
    liveUrl: 'https://mohameddk123.github.io/Car/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/Car/',
    featured: false,
    problem: 'The dealership needed a premium digital showroom that matched the quality of the vehicles they sell and generated qualified leads.',
    problemAr: 'احتاجت الوكالة إلى صالة عرض رقمية فاخرة ترقى لمستوى جودة السيارات التي تبيعها وتجلب عملاء مؤهلين.',
    solution: 'Built a sleek, dark-themed automotive website with vehicle gallery, detailed specs display, and a streamlined WhatsApp inquiry system.',
    solutionAr: 'بنينا موقع سيارات أنيق بتصميم داكن مع معرض مركبات، وعرض مواصفات تفصيلية، ونظام استفسار مبسّط عبر واتساب.',
    result: 'Qualified leads increased significantly and the website positioned the dealership as the premium choice in their market.',
    resultAr: 'ارتفعت الاستفسارات المؤهلة بشكل ملحوظ وأصبح الموقع يُعرّف الوكالة باعتبارها الخيار الفاخر في سوقها.',
    year: '2024',
    color: '#C0A060'
  },
  {
    id: 'sadatours',
    title: 'Sada Tours',
    category: 'Travel & Tourism',
    categoryAr: 'سياحة وسفر',
    shortDesc: 'A premium travel agency website with immersive visuals and a booking flow that sells packages on autopilot.',
    shortDescAr: 'موقع وكالة سياحية فاخر بمرئيات جذابة وتدفق حجز يبيع الباقات تلقائياً.',
    tags: ['Tourism', 'Travel', 'UX'],
    tagsAr: ['سياحة', 'سفر', 'تجربة مستخدم'],
    liveUrl: 'https://mohameddk123.github.io/sadatours/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/sadatours/',
    featured: true,
    problem: 'The travel agency struggled to convey their premium offering online and convert website visitors into actual bookings.',
    problemAr: 'كانت الوكالة تعاني في إيصال عرضها الفاخر رقمياً وتحويل زوار الموقع إلى حجوزات فعلية.',
    solution: 'Created an immersive travel website with stunning destination galleries, clear package presentations, and a WhatsApp-first booking system.',
    solutionAr: 'أنشأنا موقعاً سياحياً غامراً مع معارض وجهات رائعة، وعروض باقات واضحة، ونظام حجز يعتمد واتساب أساساً.',
    result: 'Direct bookings surged. The client reported the site "sells itself" — packages were being booked without any phone calls.',
    resultAr: 'ارتفعت الحجوزات المباشرة بشكل كبير. أفاد العميل بأن الموقع "يبيع نفسه" — كانت الباقات تُحجز دون أي مكالمات هاتفية.',
    year: '2024',
    color: '#0099DD'
  },
  {
    id: 'barbermah',
    title: 'Barber Mah',
    category: 'Beauty & Grooming',
    categoryAr: 'حلاقة وتجميل',
    shortDesc: 'A sleek barbershop website with service showcase and appointment flow that attracts new clients daily.',
    shortDescAr: 'موقع صالون حلاقة أنيق يعرض الخدمات ويتيح حجز المواعيد ويجذب عملاء جدداً يومياً.',
    tags: ['Beauty', 'Booking', 'Barbershop'],
    tagsAr: ['تجميل', 'حجز', 'حلاقة'],
    liveUrl: 'https://mohameddk123.github.io/Barber/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/Barber/',
    featured: false,
    problem: 'The barbershop relied entirely on word-of-mouth and needed a professional online presence to reach a broader clientele.',
    problemAr: 'كان الصالون يعتمد كلياً على التوصيات الشفهية واحتاج إلى حضور احترافي عبر الإنترنت للوصول إلى شريحة أوسع من العملاء.',
    solution: 'Built a sophisticated, dark-themed website showcasing services, pricing, and ambience — with an easy WhatsApp appointment system.',
    solutionAr: 'بنينا موقعاً راقياً بتصميم داكن يعرض الخدمات والأسعار والأجواء — مع نظام حجز مواعيد سهل عبر واتساب.',
    result: 'New client bookings increased noticeably, with many customers citing the website as the reason they chose this barbershop over competitors.',
    resultAr: 'ارتفعت حجوزات العملاء الجدد بشكل ملحوظ، وأشار كثير منهم إلى الموقع كسبب اختيارهم هذا الصالون دون المنافسين.',
    year: '2024',
    color: '#8B6914'
  },
  {
    id: 'menzahbellota',
    title: 'Menzah Bellota',
    category: 'Food & Restaurant',
    categoryAr: 'طعام ومطاعم',
    shortDesc: 'An elegant restaurant website capturing Mediterranean dining with rich visuals and a reservation-first experience.',
    shortDescAr: 'موقع مطعم راقٍ يجسّد تجربة الطعام المتوسطي بصور غنية وتجربة حجز استثنائية.',
    tags: ['Restaurant', 'Mediterranean', 'Reservations'],
    tagsAr: ['مطعم', 'متوسطي', 'حجوزات'],
    liveUrl: 'https://mohameddk123.github.io/menzahbellota/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/menzahbellota/',
    featured: false,
    problem: 'The restaurant needed a website that conveyed the warmth and authenticity of their cuisine and drove table reservations.',
    problemAr: 'احتاج المطعم إلى موقع يعكس دفء ومصداقية مطبخهم ويحفز على حجز الطاولات.',
    solution: 'Designed a warm, inviting website with beautiful food photography layouts, full menu showcase, and easy reservation system.',
    solutionAr: 'صممنا موقعاً دافئاً وجذاباً مع تخطيطات تصوير طعام رائعة، وعرض قائمة كامل، ونظام حجز سهل.',
    result: 'Weekend reservations increased notably. The client reported the website brings in exactly the right clientele.',
    resultAr: 'ارتفعت حجوزات نهاية الأسبوع بشكل ملحوظ. أفاد العميل بأن الموقع يجلب بالضبط النوع المناسب من الزبائن.',
    year: '2024',
    color: '#C17F2D'
  },
  {
    id: 'kebaprestaurant',
    title: 'Kebap Restaurant',
    category: 'Food & Restaurant',
    categoryAr: 'طعام ومطاعم',
    shortDesc: 'A vibrant restaurant website with full menu display and ordering experience that turns browsers into diners.',
    shortDescAr: 'موقع مطعم نابض بالحياة مع عرض كامل للقائمة وتجربة طلب تحوّل المتصفحين إلى زبائن.',
    tags: ['Restaurant', 'Menu', 'Food'],
    tagsAr: ['مطعم', 'قائمة طعام', 'أكل'],
    liveUrl: 'https://mohameddk123.github.io/Kebap/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/Kebap/',
    featured: false,
    problem: 'The restaurant needed to stand out in a competitive market and make their full menu easily accessible online.',
    problemAr: 'كان المطعم بحاجة للتميز في سوق تنافسية وجعل قائمته الكاملة متاحة بسهولة عبر الإنترنت.',
    solution: 'Created a vibrant, appetizing website with a complete digital menu, location info, and WhatsApp ordering integration.',
    solutionAr: 'أنشأنا موقعاً حيوياً ومشهياً مع قائمة رقمية كاملة، ومعلومات الموقع، ونظام طلب متكامل عبر واتساب.',
    result: 'Customer engagement improved and the streamlined ordering process led to higher average order values and repeat customers.',
    resultAr: 'تحسّن تفاعل العملاء وأدى نظام الطلب المبسّط إلى ارتفاع متوسط قيمة الطلبات وتكرار الزيارات.',
    year: '2024',
    color: '#E63A1E'
  },
  {
    id: 'peetshoop',
    title: "Peet's Shop",
    category: 'E-commerce & Retail',
    categoryAr: 'تجارة إلكترونية وتجزئة',
    shortDesc: 'A friendly pet shop website with product catalog and delightful UX that keeps pet owners coming back.',
    shortDescAr: 'موقع متجر حيوانات أليفة ودود مع كتالوج منتجات وتجربة مستخدم رائعة تجعل أصحاب الحيوانات يعودون دائماً.',
    tags: ['E-commerce', 'Retail', 'Pet Shop'],
    tagsAr: ['تجارة إلكترونية', 'تجزئة', 'حيوانات أليفة'],
    liveUrl: 'https://mohameddk123.github.io/pet/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/pet/',
    featured: false,
    problem: 'The pet shop needed an online presence to showcase their products and reach pet owners beyond their local neighbourhood.',
    problemAr: 'احتاج المتجر إلى حضور إلكتروني لعرض منتجاته والوصول إلى أصحاب الحيوانات خارج حيّهم المحلي.',
    solution: 'Designed a warm, friendly website with a full product catalog, category filtering, and easy contact system for orders.',
    solutionAr: 'صممنا موقعاً دافئاً وودياً مع كتالوج منتجات كامل، وتصفية حسب الفئة، ونظام تواصل سهل للطلبات.',
    result: 'Expanded the customer base and created a new revenue channel — customers now come from outside the local area.',
    resultAr: 'توسّعت قاعدة العملاء وتأسّست قناة إيرادات جديدة — أصبح العملاء يأتون من خارج المنطقة المحلية.',
    year: '2024',
    color: '#4CAF50'
  },
  {
    id: 'aqqar',
    title: 'Aqqar',
    category: 'Real Estate',
    categoryAr: 'عقارات',
    shortDesc: 'A premium real estate website that showcases properties with elegance and turns visitors into serious buyers.',
    shortDescAr: 'موقع عقارات فاخر يعرض العقارات بأناقة ويحوّل الزوار إلى مشترين جادين.',
    tags: ['Real Estate', 'Property', 'Leads'],
    tagsAr: ['عقارات', 'عقار', 'عملاء محتملون'],
    liveUrl: 'https://mohameddk123.github.io/Aqqar/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/Aqqar/',
    featured: true,
    problem: 'The real estate business needed a professional online presence to showcase their properties and generate qualified leads from serious buyers.',
    problemAr: 'احتاج المكتب العقاري إلى حضور احترافي عبر الإنترنت لعرض عقاراته وجذب عملاء محتملين جادين.',
    solution: 'Built a sophisticated real estate website with premium property listings, detailed photo galleries, and a streamlined WhatsApp inquiry system.',
    solutionAr: 'بنينا موقعاً عقارياً راقياً مع قوائم عقارات فاخرة ومعارض صور تفصيلية ونظام استفسار مبسّط عبر واتساب.',
    result: 'Qualified buyer inquiries increased significantly and the website positioned the agency as the premium choice in their market.',
    resultAr: 'ارتفعت استفسارات المشترين المؤهلين بشكل ملحوظ وأصبح الموقع يُعرّف المكتب باعتباره الخيار الأفضل في سوقه.',
    year: '2025',
    color: '#2E7D32'
  },
  {
    id: 'houseofsweets',
    title: 'House of Sweets',
    category: 'Food & Bakery',
    categoryAr: 'حلويات ومخبوزات',
    shortDesc: 'A mouthwatering bakery website with stunning pastry showcases that turns visitors into loyal, repeat customers.',
    shortDescAr: 'موقع مخبز يُسيل اللعاب مع عروض حلويات مذهلة يحوّل الزوار إلى عملاء مخلصين ومتكررين.',
    tags: ['Bakery', 'Food', 'Branding'],
    tagsAr: ['مخبوزات', 'طعام', 'هوية بصرية'],
    liveUrl: 'https://mohameddk123.github.io/Cake/',
    thumbnail: 'https://image.thum.io/get/width/800/crop/560/https://mohameddk123.github.io/Cake/',
    featured: false,
    problem: 'The bakery relied on social media but needed a professional website to build credibility and drive custom orders.',
    problemAr: 'كان المخبز يعتمد على وسائل التواصل الاجتماعي لكنه احتاج إلى موقع احترافي لبناء المصداقية وزيادة الطلبات المخصصة.',
    solution: 'Created a visually stunning bakery website with product galleries, custom order system, and brand storytelling that builds trust.',
    solutionAr: 'أنشأنا موقع مخبز بديعاً بصرياً مع معارض منتجات، ونظام طلبات مخصص، وقصة علامة تجارية تبني الثقة.',
    result: 'Custom orders increased significantly through website contact. The professional presence also attracted wholesale inquiries.',
    resultAr: 'ارتفعت الطلبات المخصصة بشكل ملحوظ عبر موقع التواصل. كما استقطب الحضور الاحترافي استفسارات بيع بالجملة.',
    year: '2024',
    color: '#F48FB1'
  }
];

const FEATURED_PROJECTS = PROJECTS.filter(p => p.featured);

const TRANSLATIONS = {
  en: {
    dir: 'ltr',
    /* ---- Navbar ---- */
    navHome:     'Home',
    navServices: 'Services',
    navProjects: 'Projects',
    navReviews:  'Reviews',
    navContact:  'Contact',
    navCta:      'Start Project',
    /* ---- Hero ---- */
    heroBadge:    'Available for New Projects',
    heroTitle:    'I Build <span class="highlight">High-Converting</span> Websites',
    heroSubtitle: 'Modern, fast, and designed to grow your business.',
    heroBtnWork:  'View My Work',
    heroBtnStart: 'Start Your Project',
    /* ---- Stats ---- */
    statsProjects:    'Projects Delivered',
    statsClients:     'Happy Clients',
    statsSatisfaction:'Client Satisfaction',
    statsYears:       'Years Experience',
    /* ---- Services ---- */
    svcLabel:    'What I Do',
    servicesTitle:   'Services',
    servicesSubtitle:'Every service is built with one goal — growing your business.',
    svc1Title: 'Website Design',
    svc1Desc:  'Custom-designed websites that look stunning and convert visitors into customers.',
    svc2Title: 'Landing Pages',
    svc2Desc:  'High-converting landing pages built to capture leads and drive sales.',
    svc3Title: 'Business Websites',
    svc3Desc:  'Professional business websites that build credibility and generate enquiries.',
    svc4Title: 'E-commerce Stores',
    svc4Desc:  'Online stores designed to sell — with seamless checkout and great UX.',
    /* ---- Projects ---- */
    projectsLabel:   'Featured Work',
    projectsTitle:   'Featured Work',
    projectsSubtitle:"A selection of projects I'm proud of. Each one built to deliver real results.",
    viewCaseStudy:   'View Case Study',
    viewAllProjects: 'View All Projects',
    livePreview:     'Live Preview',
    /* ---- All Projects page ---- */
    portfolioLabel:     'Portfolio',
    allProjectsTitle:   'All Projects',
    allProjectsSubtitle:"Every project tells a story. Here's the full collection.",
    filterAll:       'All',
    filterFitness:   'Fitness',
    filterTravel:    'Travel',
    filterRestaurant:'Restaurant',
    filterAuto:      'Automotive',
    filterBeauty:    'Beauty',
    filterEcommerce: 'E-commerce',
    filterBakery:    'Bakery',
    filterRealEstate:'Real Estate',
    /* ---- Reviews ---- */
    reviewsLabel:   'What Clients Say',
    reviewsTitle:   'What Clients Say',
    reviewsSubtitle:'Real feedback from real clients who trusted me with their business.',
    review1Name: 'Ahmed Al-Rashid',
    review1Role: 'Gym Owner, GYM TR',
    review1Text: 'Working with this developer was the best investment I made for my gym. The website looks incredible and we got 3× more enquiries in the first month alone.',
    review2Name: 'Sadia Yilmaz',
    review2Role: 'Director, Sada Tours',
    review2Text: 'Our bookings skyrocketed after the new website launched. The design perfectly captures the premium feel we wanted for our travel packages.',
    review3Name: 'Mehmet Kaya',
    review3Role: 'Owner, Car Turkey',
    review3Text: 'Professional, fast, and the result is stunning. Our clients always compliment the website. It truly represents our brand at the highest level.',
    /* ---- CTA ---- */
    ctaLabelHome:    "Let's Work Together",
    ctaLabelProjects:'Work With Me',
    ctaLabelProject: 'Start Today',
    ctaTitle:    'Ready to Build Something Great?',
    ctaSubtitle: "Let's turn your idea into a website that works hard for your business.",
    ctaBtn:      'Start Your Project on WhatsApp',
    /* ---- Footer ---- */
    footerTagline: 'Building websites that grow businesses.',
    footerRights:  'All rights reserved.',
    footerMade:    'Made with ♥ for results',
    /* ---- Project page ---- */
    problemLabel:   'The Problem',
    solutionLabel:  'The Solution',
    resultLabel:    'The Result',
    categoryLabel:  'Category:',
    yearLabel:      'Year:',
    liveWebsite:    'Visit Live Website',
    backToProjects: 'Back to Projects',
    wantSimilar:    'I Want Something Similar',
  },
  ar: {
    dir: 'rtl',
    /* ---- Navbar ---- */
    navHome:     'الرئيسية',
    navServices: 'الخدمات',
    navProjects: 'المشاريع',
    navReviews:  'التقييمات',
    navContact:  'تواصل',
    navCta:      'ابدأ مشروعك',
    /* ---- Hero ---- */
    heroBadge:    'متاح لمشاريع جديدة',
    heroTitle:    'أبني مواقع <span class="highlight">عالية التحويل</span>',
    heroSubtitle: 'حديثة، سريعة، ومصممة لتنمية عملك.',
    heroBtnWork:  'شاهد أعمالي',
    heroBtnStart: 'ابدأ مشروعك',
    /* ---- Stats ---- */
    statsProjects:    'مشروع منجز',
    statsClients:     'عميل سعيد',
    statsSatisfaction:'رضا العملاء',
    statsYears:       'سنوات خبرة',
    /* ---- Services ---- */
    svcLabel:    'ماذا أقدم',
    servicesTitle:   'الخدمات',
    servicesSubtitle:'كل خدمة مصممة بهدف واحد — تنمية عملك.',
    svc1Title: 'تصميم المواقع',
    svc1Desc:  'مواقع مصممة خصيصاً تبدو رائعة وتحول الزوار إلى عملاء.',
    svc2Title: 'صفحات الهبوط',
    svc2Desc:  'صفحات هبوط عالية التحويل مبنية لجذب العملاء المحتملين وتحقيق المبيعات.',
    svc3Title: 'مواقع الأعمال',
    svc3Desc:  'مواقع احترافية تبني المصداقية وتولد استفسارات العملاء.',
    svc4Title: 'متاجر إلكترونية',
    svc4Desc:  'متاجر مصممة للبيع — بتجربة دفع سلسة وتصميم رائع.',
    /* ---- Projects ---- */
    projectsLabel:   'أبرز الأعمال',
    projectsTitle:   'أبرز الأعمال',
    projectsSubtitle:'مختارات من مشاريعي التي أفخر بها. كل واحدة مبنية لتحقيق نتائج حقيقية.',
    viewCaseStudy:   'عرض دراسة الحالة',
    viewAllProjects: 'عرض جميع المشاريع',
    livePreview:     'معاينة مباشرة',
    /* ---- All Projects page ---- */
    portfolioLabel:     'معرض الأعمال',
    allProjectsTitle:   'جميع المشاريع',
    allProjectsSubtitle:'كل مشروع يروي قصة. هنا المجموعة الكاملة.',
    filterAll:       'الكل',
    filterFitness:   'لياقة',
    filterTravel:    'سياحة',
    filterRestaurant:'مطاعم',
    filterAuto:      'سيارات',
    filterBeauty:    'تجميل',
    filterEcommerce: 'تجارة إلكترونية',
    filterBakery:    'مخبوزات',
    filterRealEstate:'عقارات',
    /* ---- Reviews ---- */
    reviewsLabel:   'ماذا يقول العملاء',
    reviewsTitle:   'ماذا يقول العملاء',
    reviewsSubtitle:'تقييمات حقيقية من عملاء وثقوا بي في أعمالهم.',
    review1Name: 'أحمد الراشد',
    review1Role: 'مالك صالة رياضية، GYM TR',
    review1Text: 'العمل مع هذا المطور كان أفضل استثمار قمت به لصالتي الرياضية. الموقع يبدو رائعاً وحصلنا على 3 أضعاف الاستفسارات في الشهر الأول.',
    review2Name: 'سادية يلماز',
    review2Role: 'مديرة، Sada Tours',
    review2Text: 'ارتفعت حجوزاتنا بشكل كبير بعد إطلاق الموقع الجديد. التصميم يجسد تماماً الشعور الفاخر الذي أردناه لباقاتنا السياحية.',
    review3Name: 'محمد كايا',
    review3Role: 'مالك، Car Turkey',
    review3Text: 'احترافي وسريع والنتيجة مذهلة. عملاؤنا يثنون دائماً على الموقع. يمثل علامتنا التجارية بأعلى مستوى.',
    /* ---- CTA ---- */
    ctaLabelHome:    'لنعمل معاً',
    ctaLabelProjects:'اعمل معي',
    ctaLabelProject: 'ابدأ اليوم',
    ctaTitle:    'هل أنت مستعد لبناء شيء رائع؟',
    ctaSubtitle: 'دعنا نحول فكرتك إلى موقع يعمل بجد لصالح عملك.',
    ctaBtn:      'ابدأ مشروعك عبر واتساب',
    /* ---- Footer ---- */
    footerTagline: 'نبني مواقع تنمي الأعمال.',
    footerRights:  'جميع الحقوق محفوظة.',
    footerMade:    'صُنع بـ ♥ للنتائج',
    /* ---- Project page ---- */
    problemLabel:   'المشكلة',
    solutionLabel:  'الحل',
    resultLabel:    'النتيجة',
    categoryLabel:  'الفئة:',
    yearLabel:      'السنة:',
    liveWebsite:    'زيارة الموقع المباشر',
    backToProjects: 'العودة إلى المشاريع',
    wantSimilar:    'أريد شيئاً مشابهاً',
  }
};
